### PR TITLE
Input Options on Frontend for Phone Survey Answer Collection

### PR DESCRIPTION
**Pull request by rdeepak2002**
Changes:
- Fix background color of page
- Ability to re-order questions
- Modal to edit a question
- Numerous options for keypad questions (view screenshots below)
- Numerous options for voice questions (view screenshots below)

Screenshot 2023-02-10 at 4 16 03 PM

Screenshot 2023-02-10 at 4 16 14 PM

Screenshot 2023-02-10 at 4 16 23 PM

### CODE REVIEW

**Review by Skyline-9 — COMMENTED** [review]
image

Potentially risky behavior letting values go below `0`

**Review by Skyline-9 — CHANGES_REQUESTED** [review]
image
Proposal to make cards wider like so. Just need to set `width: min(90%,400px)` to something larger than `400px` like `600px`, which is shown in screenshot

**Review by Skyline-9 — APPROVED** [review]
lgtm

**Review by tanishqj123 — COMMENTED** [review]
LGTM!

**Pull request merged**
