### PR TITLE
J2TCM-35 Added Toggle Button and Fixed Upload CSV styling

### PR DESCRIPTION
**Pull request by Skyline-9**
Signed-off-by: Richard Luo <luo.richard@gmail.com>

### CODE REVIEW

**Review by rdeepak2002 — CHANGES_REQUESTED** [review]
- The CSS styling of the page breaks when having numerous questions
-  Phone recording toggling should be nested in the send survey modal because it should be configured per survey rather than globally

Screenshot 2023-02-08 at 10 46 19 AM

Screenshot 2023-02-08 at 10 46 32 AM

**Comment by Skyline-9** [comment]
Both those issues have been resolved, but i believe the build isnt refreshed. The styling is fixed in a separate PR and the button is inside the send modal

**Review by rdeepak2002 — CHANGES_REQUESTED** [review]
Can you pass the recording enabled boolean to the database object added to Firebase? I believe you would need to make changes in lines 345 (where we add a single thing to database) and near 325ish you will need to modify 'facilityInfo' to also have the recording boolean. 

Update - please just call the boolean 'record':
 
Screenshot 2023-02-09 at 5 06 38 PM

**Comment by Skyline-9** [comment]
> Can you pass the recording enabled boolean to the database object added to Firebase? I believe you would need to make changes in lines 345 (where we add a single thing to database) and near 325ish you will need to modify 'facilityInfo' to also have the recording boolean.
> 
> Update - please just call the boolean 'record':
> 
> Screenshot 2023-02-09 at 5 06 38 PM

Not familiar with your existing code, is everything just stored in facilityInfo?
image

**Review by rdeepak2002 — APPROVED** [review]
LGTM

**Review by rdeepak2002 — APPROVED** [review]

**Pull request merged**
